### ISSUE TITLE
Postgres is unavailable  - SCRAM authentication requires libpq >= 10

### ISSUE THREAD

**Issue by rkh-hash** [fossology/fossology#1932]
### Description

I'm using the docker image `fossology/fossology:3.9.0`.

Authentication failed when `scram-sha-256` is configured for password encryption on the server side (PostgreSQL server v12.2).

The reason: `SCRAM authentication requires libpq version 10 or above`.

 As specified into PostgreSQL documentation,

> Note that older clients might lack support for the SCRAM authentication mechanism, and hence not work with passwords encrypted with SCRAM-SHA-256. See Section 20.5 for more details.

(cf https://www.postgresql.org/docs/12/runtime-config-connection.html)

```shell
$ docker run --rm -it --entrypoint="" fossology/fossology:3.9.0 /bin/sh -c 'dpkg -l | grep libpq'
ii  libpq5:amd64                         9.6.19-0+deb9u1                    amd64        PostgreSQL C client library
```

#### How to reproduce

```yaml
version: '3.5'
services:
  scheduler:
    image: fossology/fossology:3.9.0
    restart: unless-stopped
    environment:
      - FOSSOLOGY_DB_HOST=db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
    command: scheduler
    depends_on:
      - db
    volumes:
      - repository:/srv/fossology/repository/
    healthcheck:
      test: ["CMD-SHELL", "true"]
      interval: 5s
      timeout: 5s
      retries: 2
  web:
    image: fossology/fossology:3.9.0
    restart: unless-stopped
    environment:
      - FOSSOLOGY_DB_HOST=db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
    command: web
    ports:
      - 8082:80
    depends_on:
      - db
      - scheduler
    volumes:
      - repository:/srv/fossology/repository/
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf localhost/repo/api/v1/version || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:12.2
    restart: unless-stopped
    environment:
      - POSTGRES_DB=fossology
      - POSTGRES_USER=fossy
      - POSTGRES_PASSWORD=fossy
      - POSTGRES_INITDB_ARGS='-E SQL_ASCII --auth-host=scram-sha-256'
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      # start-period: 10s

volumes:
  database:
  repository:
```

I've added the `--auth-host=scram-sha-256` init arg.

### Versions

* `fossology/fossology:3.9.0`

### Logs

```
$ docker logs pocfossology_web_1
psql: could not connect to server: Connection refused
        Is the server running on host "db" (172.18.0.2) and accepting
        TCP/IP connections on port 5432?
Postgres is unavailable - sleeping
psql: SCRAM authentication requires libpq version 10 or above
```
