### ISSUE TITLE
High cpu usage by DB and server is slow

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#2546]
### Description

Please describe your situation in few words here.

 Sometimes the scan is very slow. even for small package. `docker stats` shows fossology db is using more cpu than others. but ram is underutilized.  we are running our cpu in 8 cpus (4 cores/socket). Should we increase the cpu ?

#### Screenshots

![image](https://github.com/fossology/fossology/assets/4498415/f57a0f35-767b-4cbd-9170-3822d3dcfb00)

### Versions

* Last commit id on master: Version: [4.2.1.0], Branch: [HEAD], Commit: [#9a0a6e] 2022/11/15 10:13 +00:00 built @ 2023/03/21 13:22 +00:00
* Operating System (lsb_release -a): 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**Comment by dineshr93** [comment]
Hi @GMishx may I have your help on this?

**Comment by shaheemazmalmmd** [comment]
Hello @dineshr93 

You can do the following 

* Check if there are any jobs which are struck from long time and kill them. Jobs with 0 id may also occupy some space in CPU. 
* Check if the disk speed is proper.
* Check if some constantly running agents like "REUSE/UNUNPACK" are blocking all the cores. may be setting them to run on one core would create some space for other agents to run smooth.

In my opinion 8 CPU's and 4 cores/socket are enough.

**Comment by dineshr93** [comment]
Hi @shaheemazmalmmd  @GMishx   

this slowness behaviour returned now after the udpate to Version: [4.4.0], Branch: [HEAD], Commit: [#903df0] 

we noticed for package size of 14 mb the server became very slow. I tried first two option it is not a problem . I am not sure how to restrict "REUSE/UNUNPACK" to single core?

is there any other thing I should do to speed up the server? 

Regards
Dinesh

**Comment by dineshr93** [comment]
> Hi @shaheemazmalmmd @GMishx
> 
> this slowness behaviour returned now after the udpate to Version: [4.4.0], Branch: [HEAD], Commit: [#903df0]
> 
> we noticed for package size of 14 mb the server became very slow. I tried first two option it is not a problem . I am not sure how to restrict "REUSE/UNUNPACK" to single core?
> 
> is there any other thing I should do to speed up the server?
> 
> Regards Dinesh

Hi @GMishx  please may I have your help on this ? looks like server takes too long for loading files with many files.  atleast this was considerably took less time in previous version of fossy. Not sure what change in 4.4.0 has caused this slowness. Have you tested yourselves with large package (for ex: https://maven.google.com/androidx/compose/material/material-icons-extended/1.2.0-beta03/material-icons-extended-1.2.0-beta03-sources.jar)

**Comment by shaheemazmalmmd** [comment]
> > Hi @shaheemazmalmmd @GMishx
> > this slowness behaviour returned now after the udpate to Version: [4.4.0], Branch: [HEAD], Commit: [#903df0]
> > we noticed for package size of 14 mb the server became very slow. I tried first two option it is not a problem . I am not sure how to restrict "REUSE/UNUNPACK" to single core?
> > is there any other thing I should do to speed up the server?
> > Regards Dinesh
> 
> Hi @GMishx please may I have your help on this ? looks like server takes too long for loading files with many files. atleast this was considerably took less time in previous version of fossy. Not sure what change in 4.4.0 has caused this slowness. Have you tested yourselves with large package (for ex: https://maven.google.com/androidx/compose/material/material-icons-extended/1.2.0-beta03/material-icons-extended-1.2.0-beta03-sources.jar) 10 mb
> 
> To be precise by slow I mean slowness in loading the license browser page (files section ) and copyright page of that library. On flipside Scans are fast

Hello @dineshr93,

We have faced the same issues and We have found that the main reason for the slowness is having many struck/never-ending queries. We have identified them using 
```
SELECT
  pid,
  user,
  pg_stat_activity.query_start,
  now() - pg_stat_activity.query_start AS query_time,
  query,
  state,
  wait_event_type,
  wait_event
FROM pg_stat_activity
WHERE (now() - pg_stat_activity.query_start) > interval '5 minutes';
```

Once we have cleared that we see that the server is faster. I would recommend you, install the latest code(test instance) and check in if you are experiencing the same behavior. however we have added few fixes after 4.4.

**Comment by dineshr93** [comment]
Hi @shaheemazmalmmd
Thanks for your response. how to execute below command via psql inside docker? I get below error  


> ```
> SELECT
>   pid,
>   user,
>   pg_stat_activity.query_start,
>   now() - pg_stat_activity.query_start AS query_time,
>   query,
>   state,
>   wait_event_type,
>   wait_event
> FROM pg_stat_activity
> WHERE (now() - pg_stat_activity.query_start) > interval '5 minutes';
> ```

I did 
> docker exec -it e3356e1fe962 bash
and then 

![image](https://github.com/fossology/fossology/assets/4498415/7dd0a3fa-4448-474a-8b18-febce0965bde)

**Comment by shaheemazmalmmd** [comment]
> Hi @shaheemazmalmmd Thanks for your response. how to execute below command via psql inside docker? I get below error
> 
> > ```
> > SELECT
> >   pid,
> >   user,
> >   pg_stat_activity.query_start,
> >   now() - pg_stat_activity.query_start AS query_time,
> >   query,
> >   state,
> >   wait_event_type,
> >   wait_event
> > FROM pg_stat_activity
> > WHERE (now() - pg_stat_activity.query_start) > interval '5 minutes';
> > ```
> 
> I did
> 
> > docker exec -it e3356e1fe962 bash
> > and then
> 
> ![image](https://private-user-images.githubusercontent.com/4498415/334304957-7dd0a3fa-4448-474a-8b18-febce0965bde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODIxNTIsIm5iZiI6MTcxNjg4MTg1MiwicGF0aCI6Ii80NDk4NDE1LzMzNDMwNDk1Ny03ZGQwYTNmYS00NDQ4LTQ3NGEtOGIxOC1mZWJjZTA5NjViZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDczNzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQyYzBhNmE2YTFiNDljMmFlMGFlM2ZhYmMyZjVmNTQ1ZGY0ODJjZTc4NDE0OTkyNTdjNTA3NDQ5MjQ5NTcyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mBPfwmxVU28SBGhq5L0N4CBJe_nB5-VIElwvrdBWvAA)

Hello @dineshr93 ,

you can connect to database using command "psql -h localhost -p 5432 -U fossy -d fossology" and then execute the above query.

**Comment by GMishx** [comment]
As I understood, you are using the Docker Compose setup @dineshr93 , you'd have to use hostname as `db`

`psql -h db -p 5432 -U fossy -d fossology`

Other info like username and password you can get from the `docker-compose.yml` file and look for the variables `FOSSOLOGY_DB_USER` and `FOSSOLOGY_DB_PASSWORD`.

**Comment by dineshr93** [comment]
Hi @shaheemazmalmmd  

after updating the server to latest master commit Version: [4.4.0.59], Branch: [master], Commit: [#3cdeb6] the problem was not there for a while. but today we witnessed the slow loading of pages again.

also when i ran above sql query it returned 0 rows as output
![image](https://github.com/fossology/fossology/assets/4498415/d135647d-b6b4-4bf9-869e-fd5574842a59)

Hi @GMishx  
for updating the version of postgresql will updating the version here https://github.com/fossology/fossology/blob/f157388372376e7c496e3795314ef42551b3e912/docker-compose.yml#L68

and performing fresh build deploy wont suffice?

**Comment by GMishx** [comment]
@dineshr93 changing the version in compose file won't be enough as postgres data needs to be upragded as well. And that has to be done manually by first dumping the old DB, creating a new container with new mount and importing the old data.

**Comment by dineshr93** [comment]
> @dineshr93 changing the version in compose file won't be enough as postgres data needs to be upragded as well. And that has to be done manually by first dumping the old DB, creating a new container with new mount and importing the old data.

Thanks for the response. I did try to replicate steps in that url. But I am not sure where this directory exists to perform this step https://helgeklein.com/blog/upgrading-postgresql-in-docker-container/#backup-the-db-data-directory


I got the data incompatible error as mentioned in my previous comment when I tried to restore the back up.

**Comment by dineshr93** [comment]
UPDATE: DB migration from pg15 to 16 [file-pg15-16-txt](https://gist.github.com/dineshr93/d6d39d6a64167667ae26dfa0192329f5#file-pg15-16-txt)

I managed to figure out the precise steps with help of docker **shared volume** and **pg_dumpall** .  Also tried **pg_upgrade** its tricky as it requires starting of both postgres binary which is tough in case of shared volume. 

NOTE: This method throws problem while rebuilding the container https://github.com/fossology/fossology/issues/2765#issuecomment-2176975101
```
docker-compose up -d
docker stop fossology_scheduler_1 fossology_web_1
docker exec -it pg9.6 bash
psql -h db -p 5432 -U fossy -d fossology

#to check size of database

1. \l+
or
1. docker exec -it fossology_db_1 psql -U fossy -d fossology -c "select pg_database.datname as \"database name
\",pg_database_size(pg_database.datname)/1024/1024 as size_in_mb from pg_database order by size_in_mb;"


#check version: docker exec -it fossology_db_1 psql -U fossy -d fossology -c "select version(); "
#show port: show port; (optional)
#show tables: docker exec -it fossology_db_1 psql -U fossy -d fossology -c "\dt"  (optional)
#show indexes: docker exec -it fossology_db_1 psql -U fossy -d fossology -c "\di"  (optional)
#show sequences: \ds  (optional)
#quit using  \q

# to take backup
pg_dumpall --host=db --port=5432 --username=fossy --file=var/lib/postgresql/data/backups/clusterall.sql

docker-compose down

add below to docker-compose.yml below end of full db: object
=================
  db-new:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=fossology
      - POSTGRES_USER=fossy
      - POSTGRES_PASSWORD=fossy
      - PGDATA=/var/lib/postgresql/15/data
      - POSTGRES_INITDB_ARGS='-E SQL_ASCII'
    volumes:
      - database:/var/lib/postgresql/data
      - database15:/var/lib/postgresql/15/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      # start-period: 10s
volumes:
  database:
    driver: local
  repository:
  database15:
=========================
docker-compose up -d
docker stop fossology_scheduler_1 fossology_web_1
docker exec -it pg15
# backup old 15 conf 
cp var/lib/postgresql/15/data/postgresql.conf var/lib/postgresql/15/data/postgresql-old.conf
cp var/lib/postgresql/15/data/pg_hba.conf var/lib/postgresql/15/data/pg_hba-old.conf

#copy 9.6 config to 15
cp var/lib/postgresql/data/pg_hba.conf var/lib/postgresql/15/data/
cp var/lib/postgresql/data/postgresql.conf var/lib/postgresql/15/data/

restore
psql -h db-new -p 5432 -U fossy -d fossology -f /var/lib/postgresql/data/backups/clusterall.sql

docker-compose down


comment off below lines with # to docker-compose.yml below end of full db: object
=================
      #db:
      #image: postgres:9.6
      #restart: unless-stopped
      #environment:
      #- POSTGRES_DB=fossology
      #- POSTGRES_USER=fossy
      #- POSTGRES_PASSWORD=fossy
      #- POSTGRES_INITDB_ARGS='-E SQL_ASCII'
      #volumes:
      #- database:/var/lib/postgresql/data
      #healthcheck:
      #test: ["CMD-SHELL", "pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER"]
      #interval: 10s
      #timeout: 5s
      #retries: 5
      # start-period: 10s
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=fossology
      - POSTGRES_USER=fossy
      - POSTGRES_PASSWORD=fossy
      - PGDATA=/var/lib/postgresql/15/data
      - POSTGRES_INITDB_ARGS='-E SQL_ASCII'
    volumes:
            #- database:/var/lib/postgresql/data
      - database15:/var/lib/postgresql/15/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      # start-period: 10s
volumes:
        #database:
        #driver: local
  database15:
  repository:
=========================

docker-compose up -d
```

misc:
# to remove all images
`docker rmi -f $(sudo docker images -a -q)`
