### ISSUE TITLE
Scheduler is healthy but web healthcheck is returning error

### ISSUE THREAD

**Issue by csampaio26** [fossology/fossology#2583]
### Description

When running docker-compose with external database, the Scheduler is healthy with no error logs, but the healthcheck endpoint returns that the status of scheduler is error.

My docker-compose file
```
version: "3.5"
services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: fossology
    restart: unless-stopped
    environment:
      - FOSSOLOGY_DB_HOST=<DB_HOST>
      - FOSSOLOGY_DB_NAME=<DB_NAME>
      - FOSSOLOGY_DB_USER=<DB_USER>
      - FOSSOLOGY_DB_PASSWORD=<DB_PASSWORD>
    command: scheduler
    volumes:
      - repository:/srv/fossology/repository/
    healthcheck:
      test: ["CMD-SHELL", "true"]
      interval: 5s
      timeout: 5s
      retries: 2
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: fossology
    restart: unless-stopped
    environment:
      - FOSSOLOGY_DB_HOST=<DB_HOST>
      - FOSSOLOGY_DB_NAME=<DB_NAME>
      - FOSSOLOGY_DB_USER=<DB_USER>
      - FOSSOLOGY_DB_PASSWORD=<DB_PASSWORD>
    command: web
    ports:
      - "8000:80"
    depends_on:
      - scheduler
    volumes:
      - repository:/srv/fossology/repository/
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -sSf localhost:8000/repo/api/v1/health | grep -q ''{"status":"OK",'' || exit 1',
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  repository:

```

#### How to reproduce

- Run `docker-compose up -d`
- run `docker ps` to check the healthstatus

#### Screenshots

`docker ps`
<img width="1107" alt="Captura de ecrã 2023-09-13, às 14 25 08" src="https://github.com/fossology/fossology/assets/22346745/65510663-1ce7-40de-b1ed-b0e12d0820b4">

When running `curl localhost:8000/repo/api/v1/health`
<img width="486" alt="Captura de ecrã 2023-09-13, às 14 02 15" src="https://github.com/fossology/fossology/assets/22346745/312fc7ce-e90a-4545-8444-efd62d2dde60">

### Versions

* Last commit id on master: 18e87391f4c022bd43e002a1dd35630fbeacd9cd
* Operating System (lsb_release -a): AWS EC2 AMI 2

### Logs

Logs of scheduler

<img width="809" alt="Captura de ecrã 2023-09-13, às 14 25 50" src="https://github.com/fossology/fossology/assets/22346745/af29cf46-5fe6-4e2c-b451-61d1c4242c55">
